{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: valkey
    {{- include "renderTplValues" (dict "value" .Values.metrics.prometheusRule.extraLabels "indent" 4 "root" $ ) }}
  annotations:
    {{- include "renderTplValues" (dict "value" .Values.metrics.prometheusRule.extraAnnotations "indent" 4 "root" $ ) }}
spec:
{{- if .Values.metrics.prometheusRule.enabled }}
  groups:
    - name: {{ include "valkey.fullname" $ }}
      rules:
{{ tpl (toYaml .Values.metrics.prometheusRule.rules) $ | nindent 8 }}
{{- end }}
{{- end }}
